function tutorial_introduction(tutorial_dir)
% TUTORIAL_INTRODUCTION: Script that runs all the Brainstorm introduction tutorials.
%
% INPUTS: 
%    - tutorial_dir: Directory where the sample_introduction.zip file has been unzipped

% @=============================================================================
% This function is part of the Brainstorm software:
% http://neuroimage.usc.edu/brainstorm
% 
% Copyright (c)2000-2016 University of Southern California & McGill University
% This software is distributed under the terms of the GNU General Public License
% as published by the Free Software Foundation. Further details on the GPL
% license can be found at http://www.gnu.org/copyleft/gpl.html.
% 
% FOR RESEARCH PURPOSES ONLY. THE SOFTWARE IS PROVIDED "AS IS," AND THE
% UNIVERSITY OF SOUTHERN CALIFORNIA AND ITS COLLABORATORS DO NOT MAKE ANY
% WARRANTY, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF
% MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, NOR DO THEY ASSUME ANY
% LIABILITY OR RESPONSIBILITY FOR THE USE OF THIS SOFTWARE.
%
% For more information type "brainstorm license" at command prompt.
% =============================================================================@
%
% Author: Francois Tadel, 2015


% ===== FILES TO IMPORT =====
% You have to specify the folder in which the tutorial dataset is unzipped
if (nargin == 0) || isempty(tutorial_dir) || ~file_exist(tutorial_dir)
    error('The first argument must be the full path to the dataset folder.');
end
% Subject name
SubjectName = 'Subject01';
% Build the path of the files to import
AnatDir    = fullfile(tutorial_dir, 'sample_introduction', 'anatomy');
Run1File   = fullfile(tutorial_dir, 'sample_introduction', 'data', 'S01_AEF_20131218_01_600Hz.ds');
Run2File   = fullfile(tutorial_dir, 'sample_introduction', 'data', 'S01_AEF_20131218_02_600Hz.ds');
NoiseFile  = fullfile(tutorial_dir, 'sample_introduction', 'data', 'S01_Noise_20131218_02_600Hz.ds');
% Check if the folder contains the required files
if ~file_exist(Run1File)
    error(['The folder ' tutorial_dir ' does not contain the folder from the file sample_introduction.zip.']);
end



%% ===== TUTORIAL #1: CREATE PROTOCOL ================================================
%  ===================================================================================
% The protocol name has to be a valid folder name (no spaces, no weird characters...)
ProtocolName = 'TutorialIntroduction';
% Start brainstorm without the GUI
if ~brainstorm('status')
    brainstorm nogui
end
% Delete existing protocol
gui_brainstorm('DeleteProtocol', ProtocolName);
% Create new protocol
gui_brainstorm('CreateProtocol', ProtocolName, 0, 0);
% Start a new report
bst_report('Start');



%% ===== TUTORIAL #2: IMPORT ANATOMY =================================================
%  ===================================================================================
% Process: Import FreeSurfer folder
bst_process('CallProcess', 'process_import_anatomy', [], [], ...
    'subjectname', SubjectName, ...
    'mrifile',     {AnatDir, 'FreeSurfer'}, ...
    'nvertices',   15000, ...
    'nas', [127, 213, 139], ...
    'lpa', [ 52, 113,  96], ...
    'rpa', [202, 113,  91]);
% This automatically calls the SPM registration procedure because the AC/PC/IH points are not defined



%% ===== TUTORIAL #3: EXPLORE ANATOMY ================================================
%  ===================================================================================
% Get subject definition
sSubject = bst_get('Subject', SubjectName);
% Get MRI file and surface files
MriFile    = sSubject.Anatomy(sSubject.iAnatomy).FileName;
CortexFile = sSubject.Surface(sSubject.iCortex).FileName;
HeadFile   = sSubject.Surface(sSubject.iScalp).FileName;
% Display MRI
hFigMri1 = view_mri(MriFile);
hFigMri3 = view_mri_3d(MriFile, [], [], 'NewFigure');
hFigMri2 = view_mri_slices(MriFile, 'x', 20); 
pause(0.5);
% Close figures
close([hFigMri1 hFigMri2 hFigMri3]);
% Display scalp and cortex
hFigSurf = view_surface(HeadFile);
hFigSurf = view_surface(CortexFile, [], [], hFigSurf);
hFigMriSurf = view_mri(MriFile, CortexFile);
% Figure configuration
iTess = 2;
panel_surface('SetShowSulci',     hFigSurf, iTess, 1);
panel_surface('SetSurfaceColor',  hFigSurf, iTess, [1 0 0]);
panel_surface('SetSurfaceSmooth', hFigSurf, iTess, 0.5, 0);
panel_surface('SetSurfaceTransparency', hFigSurf, iTess, 0.8);
figure_3d('SetStandardView', hFigSurf, 'left');
pause(0.5);
% Close figures
close([hFigSurf hFigMriSurf]);



%% ===== TUTORIAL #4: CHANNEL FILE ===================================================
%  ===================================================================================
% Process: Create link to raw files
sFilesRun1 = bst_process('CallProcess', 'process_import_data_raw', [], [], ...
    'subjectname',  SubjectName, ...
    'datafile',     {Run1File, 'CTF'}, ...
    'channelalign', 1);
sFilesRun2 = bst_process('CallProcess', 'process_import_data_raw', [], [], ...
    'subjectname',  SubjectName, ...
    'datafile',     {Run2File, 'CTF'}, ...
    'channelalign', 1);
sFilesNoise = bst_process('CallProcess', 'process_import_data_raw', [], [], ...
    'subjectname',  SubjectName, ...
    'datafile',     {NoiseFile, 'CTF'}, ...
    'channelalign', 0);
sFilesRaw = [sFilesRun1, sFilesRun2, sFilesNoise];
% Process: Snapshot: Sensors/MRI registration
bst_process('CallProcess', 'process_snapshot', [sFilesRun1, sFilesRun2], [], ...
    'target',   1, ...  % Sensors/MRI registration
    'modality', 1, ...  % MEG (All)
    'orient',   1, ...  % left
    'comment',  'MEG/MRI Registration');

% View sensors
hFig = view_surface(HeadFile);
hFig = view_channels(sFilesRun1.ChannelFile, 'MEG', 1, 1, hFig);
% Hide sensors
pause(0.5);
hFig = view_channels(sFilesRun1.ChannelFile, 'MEG', 0, 0, hFig);
% View coils
hFig = view_channels(sFilesRun1.ChannelFile, 'CTF', 1, 1, hFig);
% View helmet
pause(0.5);
hFig = view_helmet(sFilesRun1.ChannelFile, hFig);
pause(0.5);
close(hFig);
% Edit good/bad channel for current file
gui_edit_channel(sFilesRun1.ChannelFile);
pause(0.5);
% Unload everything
bst_memory('UnloadAll', 'Forced');



%% ===== TUTORIAL #5: REVIEW RAW =====================================================
%  ===================================================================================
% Process: Convert to continuous (CTF): Continuous
bst_process('CallProcess', 'process_ctf_convert', sFilesRaw, [], ...
    'rectype', 2);  % Continuous

% View recordings
hFigMeg = view_timeseries(sFilesRun1.FileName, 'MEG');
hFigEeg = view_timeseries(sFilesRun1.FileName, 'Misc');
hFigSel = view_timeseries(sFilesRun1.FileName, 'MEG', {'MLT11','MLT12','MLT13'});
% Figure configuration
pause(0.5);
panel_record('SetTimeLength', 3);
panel_record('SetStartTime', 100);
panel_record('SetDisplayMode', hFigMeg, 'column');
panel_montage('SetCurrentMontage', hFigMeg, 'CTF LT');
% Set filters: panel_filter('SetFilters', LowPassEnabled, LowPassValue, HighPassEnabled, HighPassValue, SinRemovalEnabled, SinRemovalValue, MirrorEnabled)
panel_filter('SetFilters', 1, 100, 1, 1, 0, [], 1, 0);
pause(0.5);
panel_record('SetDisplayMode', hFigMeg, 'butterfly');
panel_montage('SetCurrentMontage', hFigMeg, '');
% Close figures
close([hFigMeg hFigEeg hFigSel]);



%% ===== TUTORIAL #8: STIM DELAYS ====================================================
%  ===================================================================================
% Process: Detect: standard_fix
bst_process('CallProcess', 'process_evt_detect_analog', [sFilesRun1, sFilesRun2], [], ...
    'eventname',   'standard_fix', ...
    'channelname', 'UADC001', ...
    'timewindow',  [], ...
    'threshold',   1.2, ...
    'blanking',    0.2, ...
    'highpass',    0, ...
    'lowpass',     0, ...
    'refevent',    'standard', ...
    'isfalling',   0, ...
    'ispullup',    0, ...
    'isclassify',  0);
% Process: Detect: deviant_fix
bst_process('CallProcess', 'process_evt_detect_analog', [sFilesRun1, sFilesRun2], [], ...
    'eventname',   'deviant_fix', ...
    'channelname', 'UADC001', ...
    'timewindow',  [], ...
    'threshold',   1.2, ...
    'blanking',    0.2, ...
    'highpass',    0, ...
    'lowpass',     0, ...
    'refevent',    'deviant', ...
    'isfalling',   0, ...
    'ispullup',    0, ...
    'isclassify',  0);
% Process: Read from channel
bst_process('CallProcess', 'process_evt_read', [sFilesRun1, sFilesRun2], [], ...
    'stimchan',  'UDIO001', ...
    'trackmode', 1, ...  % Value: detect the changes of channel value
    'zero',      0);

% Process: Delete events
bst_process('CallProcess', 'process_evt_delete', [sFilesRun1, sFilesRun2], [], ...
    'eventname', 'standard, deviant, button');
% Process: Rename event (standard_fix>standard)
bst_process('CallProcess', 'process_evt_rename', [sFilesRun1, sFilesRun2], [], ...
    'src',  'standard_fix', ...
    'dest', 'standard');
% Process: Rename event (deviant_fix>deviant)
bst_process('CallProcess', 'process_evt_rename', [sFilesRun1, sFilesRun2], [], ...
    'src',  'deviant_fix', ...
    'dest', 'deviant');
% Process: Rename event (64>button)
bst_process('CallProcess', 'process_evt_rename', [sFilesRun1, sFilesRun2], [], ...
    'src',  '64', ...
    'dest', 'button');



%% ===== TUTORIAL #10: FREQUENCY FILTERS =============================================
%  ===================================================================================
% Process: Sinusoid removal: 60Hz 120Hz 180Hz 300Hz
sFilesNotch = bst_process('CallProcess', 'process_notch', sFilesRaw, [], ...
    'freqlist',    [60, 120, 180], ...
    'sensortypes', 'MEG', ...
    'read_all',    0);
% Process: Power spectrum density (Welch)
sFilesPsd = bst_process('CallProcess', 'process_psd', [sFilesRaw, sFilesNotch], [], ...
    'timewindow',  [], ...
    'win_length',  4, ...
    'win_overlap', 50, ...
    'clusters',    {}, ...
    'sensortypes', 'MEG', ...
    'edit', struct(...
         'Comment',    'Power', ...
         'TimeBands',  [], ...
         'Freqs',      [], ...
         'ClusterFuncTime', 'none', ...
         'Measure',    'power', ...
         'Output',     'all', ...
         'SaveKernel', 0));
% Process: Snapshot: Frequency spectrum
bst_process('CallProcess', 'process_snapshot', sFilesPsd, [], ...
    'target',   10, ...  % Frequency spectrum
    'modality', 1, ...   % MEG (All)
    'comment',  'Power spectrum density');
% Process: Delete folders
bst_process('CallProcess', 'process_delete', sFilesRaw, [], ...
    'target', 2);  % Delete folders
% Separate the three outputs
sFilesRun1  = {sFilesNotch(1).FileName};
sFilesRun2  = {sFilesNotch(2).FileName};
sFilesNoise = {sFilesNotch(3).FileName};



%% ===== TUTORIAL #11: BAD CHANNELS ==================================================
%  ===================================================================================
% % Mark bad channels
% tree_set_channelflag(sFilesRun2.FileName, 'AddBad', 'MRT51, MLO52, MLO42, MLO43');
% % Process: Set bad channels
% sFiles = bst_process('CallProcess', 'process_channel_setbad', sFilesRun2, [], ...
%     'sensortypes', 'MRT51, MLO52, MLO42, MLO43');



%% ===== TUTORIAL #12: ARTIFACTS DETECTION ===========================================
%  ===================================================================================
% Process: Detect heartbeats
bst_process('CallProcess', 'process_evt_detect_ecg', [sFilesRun1, sFilesRun2], [], ...
    'channelname', 'ECG', ...
    'timewindow',  [], ...
    'eventname',   'cardiac');
% Process: Detect eye blinks
bst_process('CallProcess', 'process_evt_detect_eog',  [sFilesRun1, sFilesRun2], [], ...
    'channelname', 'VEOG', ...
    'timewindow',  [], ...
    'eventname',   'blink');
% Process: Remove simultaneous
bst_process('CallProcess', 'process_evt_remove_simult', [sFilesRun1, sFilesRun2], [], ...
    'remove', 'cardiac', ...
    'target', 'blink', ...
    'dt',     0.25, ...
    'rename', 0);



%% ===== TUTORIAL #13: SSP ===========================================================
%  ===================================================================================
% Process: SSP ECG: cardiac
bst_process('CallProcess', 'process_ssp_ecg', [sFilesRun1, sFilesRun2], [], ...
    'eventname',   'cardiac', ...
    'sensortypes', 'MEG', ...
    'usessp',      0, ...
    'select',      1);
% Process: SSP EOG: blink
bst_process('CallProcess', 'process_ssp_eog', sFilesRun1, [], ...
    'eventname',   'blink', ...
    'sensortypes', 'MEG', ...
    'usessp',      0, ...
    'select',      [1 2]);
bst_process('CallProcess', 'process_ssp_eog', sFilesRun2, [], ...
    'eventname',   'blink', ...
    'sensortypes', 'MEG', ...
    'usessp',      0, ...
    'select',      1);


%% ===== TUTORIAL #14: BAD SEGMENTS ==================================================
%  ===================================================================================
% Process: Detect other artifacts
bst_process('CallProcess', 'process_evt_detect_badsegment', [sFilesRun1, sFilesRun2], [], ...
    'timewindow',  [], ...
    'sensortypes', 'MEG', ...
    'threshold',   3, ...  % 3
    'isLowFreq',   1, ...
    'isHighFreq',  1);

% Process: Rename event (1-7Hz > saccade)  (Run02 only)
bst_process('CallProcess', 'process_evt_rename', sFilesRun2, [], ...
    'src',  '1-7Hz', ...
    'dest', 'saccade');

% Manual selection of saccades (cannot be done from the pipeline editor: manual edition of the structures)
sMatRun2 = in_bst_data(sFilesRun2.FileName, 'F');
iEvtSaccade = find(strcmpi({sMatRun2.F.events.label}, 'saccade'));
sMatRun2.F.events(iEvtSaccade).times   = [30, 81.5, 104, 142.5, 167, 187.5, 246.5, 319;  31, 83, 105, 144, 168, 188.5, 248, 320];
sMatRun2.F.events(iEvtSaccade).samples = [18000, 48900, 62400, 85500, 100200, 112500, 147900, 191400;  18600, 49800, 63000, 86400, 100800, 113100, 148800, 192000];
sMatRun2.F.events(iEvtSaccade).epochs  = ones(1, size(sMatRun2.F.events(iEvtSaccade).times, 2));
bst_save(file_fullpath(sFilesRun2.FileName), sMatRun2, 'v6', 1);

% Process: SSP: saccade  (Run02 only)
bst_process('CallProcess', 'process_ssp', sFilesRun2, [], ...
    'timewindow',  [], ...
    'eventname',   'saccade', ...
    'eventtime',   [-0.2, 0.2], ...
    'bandpass',    [1.5, 7], ...
    'sensortypes', 'MEG', ...
    'usessp',      1, ...
    'saveerp',     0, ...
    'method',      1, ...
    'select',      1);
% Process: Detect other artifacts  (Run02 only)
bst_process('CallProcess', 'process_evt_detect_badsegment', sFilesRun2, [], ...
    'timewindow',  [], ...
    'sensortypes', 'MEG', ...
    'threshold',   3, ...  % 3
    'isLowFreq',   1, ...
    'isHighFreq',  1);

% Process: Rename event (1-7Hz > bad_1-7Hz)
bst_process('CallProcess', 'process_evt_rename', [sFilesRun1, sFilesRun2], [], ...
    'src',  '1-7Hz', ...
    'dest', 'bad_1-7Hz');
% Process: Rename event (40-240Hz > bad_40-240Hz)
bst_process('CallProcess', 'process_evt_rename', [sFilesRun1, sFilesRun2], [], ...
    'src',  '40-240Hz', ...
    'dest', 'bad_40-240Hz');
% Process: Snapshot: SSP projectors
bst_process('CallProcess', 'process_snapshot', [sFilesRun1, sFilesRun2], [], ...
    'target',  2, ...  % SSP projectors
    'comment', 'SSP projectors');



%% ===== TUTORIAL #15: IMPORT EVENTS =================================================
%  ===================================================================================
% Process: Import MEG/EEG: Events (Run01)
sFilesEpochs1 = bst_process('CallProcess', 'process_import_data_event', sFilesRun1, [], ...
    'subjectname', SubjectName, ...
    'condition',   '', ...
    'eventname',   'standard, deviant', ...
    'timewindow',  [], ...
    'epochtime',   [-0.100, 0.500], ...
    'createcond',  0, ...
    'ignoreshort', 1, ...
    'usectfcomp',  1, ...
    'usessp',      1, ...
    'freq',        [], ...
    'baseline',    [-0.1, 0]);
% Process: Import MEG/EEG: Events (Run02)
sFilesEpochs2 = bst_process('CallProcess', 'process_import_data_event', sFilesRun2, [], ...
    'subjectname', SubjectName, ...
    'condition',   '', ...
    'eventname',   'standard, deviant', ...
    'timewindow',  [], ...
    'epochtime',   [-0.100, 0.500], ...
    'createcond',  0, ...
    'ignoreshort', 1, ...
    'usectfcomp',  1, ...
    'usessp',      1, ...
    'freq',        [], ...
    'baseline',    [-0.1, 0]);
% Display raster plot
hFigRaster = view_erpimage({sFilesRun1.FileName}, 'MEG', 'erpimage');
bst_report('Snapshot', hFigRaster, sFilesRun1(1).FileName, 'ERP image');
close(hFigRaster);


%% ===== TUTORIAL #16: AVERAGE =======================================================
%  ===================================================================================
% Process: Select uniform number of trials: By trial group (folder)
sFilesAvg = bst_process('CallProcess', 'process_select_uniform', [sFilesEpochs1, sFilesEpochs2], [], ...
    'group',  2, ...  % By trial group (folder)
    'nfiles', 0, ...
    'method', 4);     % Uniformly distributed
% Process: Average: By trial group (folder average)
sFilesAvg = bst_process('CallProcess', 'process_average', sFilesAvg, [], ...
    'avgtype',    5, ...  % By trial groups (folder average)
    'avg_func',   1, ...  % Arithmetic average: mean(x)
    'weighted',   0, ...
    'keepevents', 1);
% Process: Delete events 'cardiac'
bst_process('CallProcess', 'process_evt_delete', sFilesAvg, [], ...
    'eventname', 'cardiac');
% Process: Snapshot: Recordings time series
bst_process('CallProcess', 'process_snapshot', sFilesAvg, [], ...
    'target',     5, ...  % Recordings time series
    'modality',   1, ...  % MEG (All)
    'comment',    'Evoked response');
% Process: Snapshot: Recordings topography (contact sheet)
bst_process('CallProcess', 'process_snapshot', sFilesAvg, [], ...
    'target',         7, ...  % Recordings topography (contact sheet)
    'modality',       1, ...  % MEG
    'contact_time',   [0, 0.350], ...
    'contact_nimage', 15, ...
    'comment',        'Evoked response');



%% ===== TUTORIAL #17: EXPLORATION ===================================================
%  ===================================================================================
% View averages
hFigMeg1  = view_timeseries(sFilesAvg(1).FileName, 'MEG');
hFigMeg2  = view_timeseries(sFilesAvg(2).FileName, 'MEG');
hFigEeg1  = view_timeseries(sFilesAvg(1).FileName, 'Misc');
hFigEeg2  = view_timeseries(sFilesAvg(2).FileName, 'Misc');
hFigTopo1 = view_topography(sFilesAvg(1).FileName, 'MEG', '2DSensorCap');
hFigTopo2 = view_topography(sFilesAvg(2).FileName, 'MEG', '2DSensorCap');
hFigTp2   = view_topography(sFilesAvg(3).FileName, 'MEG', '3DSensorCap');
hFigTp3   = view_topography(sFilesAvg(3).FileName, 'MEG', '2DDisc');
hFigTp4   = view_topography(sFilesAvg(3).FileName, 'MEG', '2DLayout');
% Set time: 90ms
panel_time('SetCurrentTime', 0.090);
% Set filters: 100Hz low-pass, no high-pass
panel_filter('SetFilters', 1, 100, 0, [], 0, [], 1, 0);
% View selected sensors
SelectedChannels = {'MLC31', 'MLC32'};
bst_figures('SetSelectedRows', SelectedChannels);
view_timeseries(sFilesAvg(4).FileName, [], SelectedChannels);
% Select time window
figure_timeseries('SetTimeSelectionManual', hFigMeg1, [0.070, 0.130]);
% Show sensors on 2DSensorCap topography
isMarkers = 1;
isLabels = 0;
figure_3d('ViewSensors', hFigTopo1, isMarkers, isLabels);
% Display time contact sheet for a figure
pause(0.5);
hContactFig = view_contactsheet( hFigTopo2, 'time', 'fig', [], 12, [0 0.120] );
pause(0.5);
close(hContactFig);



%% ===== TUTORIAL #18: COLORMAPS =====================================================
%  ===================================================================================
ColormapType = 'meg';
% Set 'Meg' colormap to 'jet'
bst_colormaps('SetColormapName', ColormapType, 'jet');
pause(0.5);
% Set 'Meg' colormap to 'rwb'
bst_colormaps('SetColormapName', ColormapType, 'cmap_rbw');
% Set colormap to display absolute values
bst_colormaps('SetColormapAbsolute', ColormapType, 1);
% Normalize colormap for each time frame
bst_colormaps('SetMaxMode', ColormapType, 'local');
% Hide colorbar
bst_colormaps('SetDisplayColorbar', ColormapType, 0);
pause(0.5);
% Restore colormap to default values
bst_colormaps('RestoreDefaults', ColormapType);
% Edit good/bad channel for current file
gui_edit_channelflag(sFilesAvg(1).FileName);
% Close figures
pause(0.5);
bst_memory('UnloadAll', 'Forced');



%% ===== TUTORIAL #20: HEAD MODEL ====================================================
%  ===================================================================================
% Process: Compute head model
bst_process('CallProcess', 'process_headmodel', sFilesAvg, [], ...
    'comment',      '', ...
    'sourcespace',  1, ...
    'meg',          3);  % Overlapping spheres
% Get study structure
sStudy = bst_get('Study', sFilesAvg(1).iStudy);
% Show spheres
hFig = view_spheres(sStudy.HeadModel(sStudy.iHeadModel).FileName, sStudy.Channel.FileName, sSubject);
pause(0.5);
close(hFig);



%% ===== TUTORIAL #21: NOISE COVARIANCE ==============================================
%  ===================================================================================
% Process: Compute noise covariance
bst_process('CallProcess', 'process_noisecov', sFilesNoise, [], ...
    'baseline', [], ...
    'target',   1, ...  % Noise covariance
    'dcoffset', 1, ...  % Block by block, to avoid effects of slow shifts in data
    'method',   1, ...  % Full noise covariance matrix
    'copycond', 1, ...
    'copysubj', 0);
% Process: Snapshot: Noise covariance
bst_process('CallProcess', 'process_snapshot', sFilesNoise, [], ...
    'target',  3, ...  % Noise covariance
    'comment', 'Noise covariance');

% Process: Compute data covariance [Run01]
bst_process('CallProcess', 'process_noisecov', sFilesEpochs1, [], ...
    'baseline', [0.050, 0.150], ...
    'target',   2, ...  % Data covariance
    'dcoffset', 1, ...  % Block by block, to avoid effects of slow shifts in data
    'method',   1, ...  % Full noise covariance matrix
    'copycond', 0, ...
    'copysubj', 0);
% Process: Compute data covariance [Run02]
bst_process('CallProcess', 'process_noisecov', sFilesEpochs2, [], ...
    'baseline', [0.050, 0.150], ...
    'target',   2, ...  % Data covariance
    'dcoffset', 1, ...  % Block by block, to avoid effects of slow shifts in data
    'method',   1, ...  % Full noise covariance matrix
    'copycond', 0, ...
    'copysubj', 0);
% Process: Snapshot: Data covariance
bst_process('CallProcess', 'process_snapshot', [sFilesEpochs1(1), sFilesEpochs2(1)], [], ...
    'target',  12, ...  % Data covariance
    'comment', 'Data covariance');



%% ===== TUTORIAL #22: SOURCE ESTIMATION =============================================
%  ===================================================================================
% === GET DEVIANT AVERAGE RUN01 ===
% Process: Select recordings in: Subject01/S01_AEF_20131218_01_600Hz_notch
sFilesAvg01 = bst_process('CallProcess', 'process_select_files_data', [], [], ...
    'subjectname', SubjectName, ...
    'condition',   'S01_AEF_20131218_01_600Hz_notch', ...
    'includebad',  0);
% Process: Select file comments with tag: deviant
sFilesAvgDeviant01 = bst_process('CallProcess', 'process_select_tag', sFilesAvg01, [], ...
    'tag',    'Avg: deviant', ...
    'search', 2, ...  % Search the file comments
    'select', 1);     % Select only the files with the tag

% === CONSTRAINED EXAMPLE ===
% Minimum norm options
InverseOptions = struct(...
    'Comment',        'MN: MEG', ...
    'InverseMethod',  'minnorm', ...
    'InverseMeasure', 'amplitude', ...
    'SourceOrient',   {{'fixed'}}, ...
    'Loose',          0.2, ...
    'UseDepth',       1, ...
    'WeightExp',      0.5, ...
    'WeightLimit',    10, ...
    'NoiseMethod',    'reg', ...
    'NoiseReg',       0.1, ...
    'SnrMethod',      'fixed', ...
    'SnrRms',         0.001, ...
    'SnrFixed',       9, ...
    'ComputeKernel',  1, ...
    'DataTypes',      {{'MEG'}});
% Process: Compute sources [2015]
sFilesSrcDeviant01 = bst_process('CallProcess', 'process_inverse_2015', sFilesAvgDeviant01, [], ...
    'output',  2, ...  % Kernel only: one per file
    'inverse', InverseOptions);

% === DISPLAY SOURCES MANUALLY ===
% View time series
hFigSrc1 = view_timeseries(sFilesAvgDeviant01(1).FileName, 'MEG');
% View on the cortex surface
hFigSrc2 = script_view_sources(sFilesSrcDeviant01(1).FileName, 'cortex');
% Set current time to 90ms
panel_time('SetCurrentTime', 0.090);
% Set orientation
figure_3d('SetStandardView', hFigSrc2, 'left');
% Set surface threshold to 75% of the maximal value
iSurf = 1;
thresh = .60; 
panel_surface('SetDataThreshold', hFigSrc2, iSurf, thresh);
% Set surface smoothing
panel_surface('SetSurfaceSmooth', hFigSrc2, iSurf, .6, 0);
% Show sulci
panel_surface('SetShowSulci', hFigSrc2, iSurf, 1);

% View sources on MRI (3D orthogonal slices)
hFigSrc3 = script_view_sources(sFilesSrcDeviant01(1).FileName, 'mri3d');
panel_surface('SetDataThreshold', hFigSrc3, iSurf, thresh);
% Set the position of the cuts in the 3D figure
cutsPosVox = [74 93 159];
panel_surface('PlotMri', hFigSrc3, cutsPosVox);

% View sources with MRI Viewer
hFigSrc4 = script_view_sources(sFilesSrcDeviant01(1).FileName, 'mriviewer');
panel_surface('SetDataThreshold', hFigSrc4, iSurf, thresh);
% Set the position of the cuts in the MRI Viewer (values in millimeters)
figure_mri('SetLocation', 'voxel', hFigSrc4, [], cutsPosVox);
% Close figures
close([hFigSrc1 hFigSrc2 hFigSrc3 hFigSrc4]);

% === UNCONSTRAINED SHARED ===
% Unconstrained minnorm
InverseOptions.Comment        = 'MN: MEG';
InverseOptions.InverseMeasure = 'amplitude';
InverseOptions.SourceOrient   = {'free'};
% Process: Compute sources [2015]
sFilesAvgSrc = bst_process('CallProcess', 'process_inverse_2015', sFilesAvg, [], ...
    'output',  1, ...  % Kernel only: shared
    'inverse', InverseOptions);

% === NORMALIZED SOURCES ===
% dSPM
InverseOptions.Comment        = 'dSPM: MEG';
InverseOptions.InverseMeasure = 'dspm';
sFilesSrcDspm = bst_process('CallProcess', 'process_inverse_2015', sFilesAvg(1), [], ...
    'output',  2, ...  % Kernel only: one per file
    'inverse', InverseOptions);
% MNp
InverseOptions.Comment        = 'MNp: MEG';
InverseOptions.InverseMeasure = 'performance';
sFilesSrcMnp = bst_process('CallProcess', 'process_inverse_2015', sFilesAvg(1), [], ...
    'output',  2, ...  % Kernel only: one per file
    'inverse', InverseOptions);
% sLORETA (old function)
sFilesSrcSloreta = bst_process('CallProcess', 'process_inverse', sFilesAvg(1), [], ...
    'comment', '', ...
    'method',  3, ...  % sLORETA
    'wmne', struct(...
         'SourceOrient', {{'free'}}, ...
         'loose',        0.2, ...
         'SNR',          3, ...
         'pca',          1, ...
         'diagnoise',    0, ...
         'regnoise',     1, ...
         'magreg',       0.1, ...
         'gradreg',      0.1, ...
         'depth',        1, ...
         'weightexp',    0.5, ...
         'weightlimit',  10), ...
    'sensortypes', 'MEG, MEG MAG, MEG GRAD, EEG', ...
    'output', 2);  % Kernel only: one per file
% Process: Z-score normalization: [-100ms,-2ms]
sFilesSrcZscore = bst_process('CallProcess', 'process_zscore_dynamic', sFilesAvgSrc(1), [], ...
    'baseline',   [-0.100, -0.002], ...
    'source_abs', 1, ...
    'dynamic',    0);

% Process: Snapshot: Sources (one time)
bst_process('CallProcess', 'process_snapshot', sFilesAvgSrc(1), [], ...
    'target',    8, ...  % Sources (one time)
    'orient',    1, ...  % left
    'time',      0.09, ...
    'threshold', 40, ...
    'comment',   'Current density map');
bst_process('CallProcess', 'process_snapshot', sFilesSrcDspm, [], ...
    'target',    8, ...  % Sources (one time)
    'orient',    1, ...  % left
    'time',      0.09, ...
    'threshold', 40, ...
    'comment',   'dSPM');
bst_process('CallProcess', 'process_snapshot', sFilesSrcSloreta, [], ...
    'target',    8, ...  % Sources (one time)
    'orient',    1, ...  % left
    'time',      0.09, ...
    'threshold', 40, ...
    'comment',   'sLORETA');
bst_process('CallProcess', 'process_snapshot', sFilesSrcMnp, [], ...
    'target',    8, ...  % Sources (one time)
    'orient',    1, ...  % left
    'time',      0.09, ...
    'threshold', 40, ...
    'comment',   'MNp');
bst_process('CallProcess', 'process_snapshot', sFilesSrcZscore, [], ...
    'target',    8, ...  % Sources (one time)
    'orient',    1, ...  % left
    'time',      0.09, ...
    'threshold', 40, ...
    'comment',   'Z-score');

% === DELETE EXPERIMENTS ===
% Process: Delete constrained example
bst_process('CallProcess', 'process_delete', [sFilesSrcDeviant01, sFilesSrcDspm, sFilesSrcSloreta, sFilesSrcMnp, sFilesSrcZscore], [], ...
    'target', 1);  % Delete data files

% === AVERAGE SOURCES ===
% Get new structures for the file names
sFilesAvgSrc = bst_process('GetInputStruct', {sFilesAvgSrc.FileName});
% Process: Average: By trial group (subject average)
sFilesIntraSrc = bst_process('CallProcess', 'process_average', sFilesAvgSrc, [], ...
    'avgtype',  6, ...  % By trial group (subject average)
    'weighted', 1, ...
    'avg_func', 1, ...  % Arithmetic average: mean(x)
    'scalenormalized', 0);
% Process: Low-pass:40Hz
sFilesIntraSrcLow = bst_process('CallProcess', 'process_bandpass', sFilesIntraSrc, [], ...
    'highpass',  0, ...
    'lowpass',   40, ...
    'mirror',    1, ...
    'overwrite', 0);
% Process: Z-score normalization: [-100ms,-2ms]
sFilesIntraZscore = bst_process('CallProcess', 'process_zscore_dynamic', sFilesIntraSrcLow, [], ...
    'baseline',   [-0.075, -0.002], ...
    'source_abs', 1, ...
    'dynamic',    0);
% Process: Delete intermediate results
bst_process('CallProcess', 'process_delete', sFilesIntraSrcLow, [], ...
    'target', 1);  % Delete data files
% Screen captures
bst_process('CallProcess', 'process_snapshot', sFilesIntraZscore, [], ...
    'target',    8, ...  % Sources (one time)
    'orient',    1, ...  % left
    'time',      0.09, ...
    'threshold', 40, ...
    'comment',   'Re-averaged Z-score (left)');
bst_process('CallProcess', 'process_snapshot', sFilesIntraZscore, [], ...
    'target',    8, ...  % Sources (one time)
    'orient',    2, ...  % right
    'time',      0.09, ...
    'threshold', 40, ...
    'comment',   'Re-averaged Z-score (right)');
bst_process('CallProcess', 'process_snapshot', sFilesIntraZscore(1), [], ...
    'target',         9, ...  % Sources (contact sheet)
    'orient',         1, ...  % left
    'contact_time',   [0, 0.35], ...
    'contact_nimage', 15, ...
    'threshold',      20, ...
    'comment',        'Re-averaged Z-score');


%% ===== TUTORIAL #23: SCOUTS ========================================================
%  ===================================================================================
% Load surface file
sCortex = in_tess_bst(CortexFile);
% Add new scouts in first atlas
sCortex.iAtlas = find(strcmpi({sCortex.Atlas.Name}, 'Destrieux'));
% Save file
bst_save(file_fullpath(CortexFile), sCortex, 'v7');
% Unload everything
bst_memory('UnloadAll', 'Forced');
% Find scouts indices to display: {'A1L', 'A1R', 'IFGL', 'M1L', 'SMAL', 'PPCR'}
[tmp,iScouts,tmp] = intersect({sCortex.Atlas(sCortex.iAtlas).Scouts.Label}, {'G_temp_sup-G_T_transv L', 'G_temp_sup-G_T_transv R', 'G_front_inf-Opercular L', 'G_precentral L', 'G_front_sup L', 'S_intrapariet_and_P_trans R'});

% View cortex
hFigSurf1 = view_surface(CortexFile, [], [], 'NewFigure');
hFigSurf2 = view_surface(CortexFile, [], [], 'NewFigure');
figure_3d('SetStandardView', hFigSurf1, 'left');
figure_3d('SetStandardView', hFigSurf2, 'right');
panel_surface('SetSurfaceSmooth', hFigSurf1, 1, .6, 0);
panel_surface('SetSurfaceSmooth', hFigSurf2, 1, .6, 0);
panel_surface('SetShowSulci', hFigSurf1, 1, 1);
panel_surface('SetShowSulci', hFigSurf2, 1, 1);
% Configure scouts display
panel_scout('SetScoutsOptions', 0, 1, 1, 'all', 0.7, 1, 1, 0);
% View scouts
hFigScouts = view_scouts({sFilesIntraZscore.FileName}, iScouts);
% Save figures
bst_report('Snapshot', [hFigSurf1 hFigSurf2 hFigScouts], sFilesIntraZscore(1).FileName, 'Scouts');
% Close all
pause(1);
bst_memory('UnloadAll', 'Forced');



%% ===== TUTORIAL #24: TIME-FREQUENCY ================================================
%  ===================================================================================
% Process: Time-frequency (Morlet wavelets)
sFilesTf1 = bst_process('CallProcess', 'process_timefreq', sFilesAvg(1), [], ...
    'sensortypes', 'MEG', ...
    'normalize', 0, ...
    'edit', struct(...
         'Comment', 'Power,1-150Hz', ...
         'TimeBands', [], ...
         'Freqs', [1, 2, 3.1, 4.2, 5.4, 6.7, 8, 9.5, 11, 12.6, 14.3, 16.1, 18.1, 20.1, 22.3, 24.6, 27, 29.6, 32.4, 35.3, 38.4, 41.6, 45.1, 48.8, 52.7, 56.9, 61.3, 66, 70.9, 76.2, 81.8, 87.7, 94, 100.6, 107.7, 115.2, 123.1, 131.6, 140.5, 150], ...
         'MorletFc', 1, ...
         'MorletFwhmTc', 3, ...
         'ClusterFuncTime', 'none', ...
         'Measure', 'power', ...
         'Output', 'all', ...
         'SaveKernel', 0));
     
% View time-frequency file
hFigTf1 = view_timefreq(sFilesTf1.FileName, 'SingleSensor');
% Configure display
sOptions = panel_display('GetDisplayOptions');
sOptions.HideEdgeEffects = 1;
sOptions.HighResolution = 1;
panel_display('SetDisplayOptions', sOptions);
% Other display modes
hFigTf2 = view_timefreq(sFilesTf1.FileName, 'AllSensors');
hFigTf3 = view_timefreq(sFilesTf1.FileName, '2DLayout');
hFigTf4 = view_timefreq(sFilesTf1.FileName, '2DLayoutOpt');
bst_report('Snapshot', [hFigTf1 hFigTf2 hFigTf3 hFigTf4], sFilesTf1.FileName, 'Time-frequency');
close([hFigTf1 hFigTf2 hFigTf3 hFigTf4]);
% Topographies
hFigTf5  = view_topography(sFilesTf1.FileName, 'MEG', '3DSensorCap');
hFigTf6  = view_topography(sFilesTf1.FileName, 'MEG', '2DDisc');
hFigTf7  = view_topography(sFilesTf1.FileName, 'MEG', '2DSensorCap');
hFigTf8  = view_topography(sFilesTf1.FileName, 'MEG', '2DLayout');
hFigTf9  = view_spectrum(sFilesTf1.FileName, 'Spectrum');
hFigTf10 = view_spectrum(sFilesTf1.FileName, 'TimeSeries');
panel_time('SetCurrentTime', 0.090);
panel_freq('SetCurrentFreq', 8);
bst_report('Snapshot', [hFigTf5 hFigTf6 hFigTf7 hFigTf8 hFigTf9 hFigTf10], sFilesTf1.FileName, 'Time-frequency');
bst_memory('UnloadAll', 'Forced');

% === AVERAGE FOR SCOUTS ===
% Select all sources for the single deviant epochs
sFilesEpochDeviantSrc = bst_process('CallProcess', 'process_select_files_results', [], [], ...
    'subjectname', SubjectName, ...
    'condition',   '', ...
    'includebad',  0);
sFilesEpochDeviantSrc = bst_process('CallProcess', 'process_select_tag', sFilesEpochDeviantSrc, [], ...
    'tag',    'deviant', ...
    'search', 1, ...  % Search the file names
    'select', 1);     % Select only the files with the tag
sFilesEpochDeviantSrc = bst_process('CallProcess', 'process_select_tag', sFilesEpochDeviantSrc, [], ...
    'tag',    'average', ...
    'search', 1, ...  % Search the file names
    'select', 2);     % Exclude the files with the tag

% Process: Time-frequency (Morlet wavelets)
sFilesTfScout = bst_process('CallProcess', 'process_timefreq', sFilesEpochDeviantSrc, [], ...
    ... % 'clusters',   {'User scouts', {'A1L', 'IFGL', 'M1L'}}, ...
    'clusters',   {'Destrieux', {'G_temp_sup-G_T_transv L', 'G_front_inf-Opercular L', 'G_precentral L'}}, ...
    'scoutfunc',  1, ...  % Mean
    'normalize',  0, ...
    'edit', struct(...
         'Comment',         'Deviant: Scouts,Avg,Power,1-150Hz', ...
         'TimeBands',       [], ...
         'Freqs',           [1, 2, 3.1, 4.2, 5.4, 6.7, 8, 9.5, 11, 12.6, 14.3, 16.1, 18.1, 20.1, 22.3, 24.6, 27, 29.6, 32.4, 35.3, 38.4, 41.6, 45.1, 48.8, 52.7, 56.9, 61.3, 66, 70.9, 76.2, 81.8, 87.7, 94, 100.6, 107.7, 115.2, 123.1, 131.6, 140.5, 150], ...
         'MorletFc',        1, ...
         'MorletFwhmTc',    3, ...
         'ClusterFuncTime', 'after', ...
         'Measure',         'power', ...
         'Output',          'average', ...
         'SaveKernel',      0));
% Process: Z-score normalization: [-100ms,-2ms]
sFilesTfScoutZscore = bst_process('CallProcess', 'process_zscore_dynamic', sFilesTfScout, [], ...
    'baseline', [-0.100, -0.002]);
% Process: Event related perturbation: [-100ms,-2ms]
sFilesTfScoutErsd = bst_process('CallProcess', 'process_ersd', sFilesTfScout, [], ...
    'baseline', [-0.100, -0.002], ...
    'overwrite', 0);

% Display results
hFigTf1 = view_timefreq(sFilesTfScoutZscore.FileName, 'AllSensors');
hFigTf2 = view_timefreq(sFilesTfScoutErsd.FileName, 'AllSensors');
bst_report('Snapshot', hFigTf1, sFilesTfScoutZscore.FileName, 'Time-frequency: Z-score');
bst_report('Snapshot', hFigTf1, sFilesTfScoutErsd.FileName, 'Time-frequency: ERD/ERS');
bst_memory('UnloadAll', 'Forced');

% === FULL CORTEX / HILBERT ===
% Process: Hilbert transform
sFilesHilbert = bst_process('CallProcess', 'process_hilbert', sFilesAvgSrc(1), [], ...
    'clusters', {}, ...
    'scoutfunc', 1, ...  % Mean
    'mirror', 1, ...
    'normalize', 0, ...
    'edit', struct(...
         'Comment', 'Magnitude', ...
         'TimeBands', [], ...
         'Freqs', {{'delta', '2, 4', 'mean'; 'theta', '5, 7', 'mean'; 'alpha', '8, 12', 'mean'; 'beta', '15, 29', 'mean'; 'gamma1', '30, 59', 'mean'; 'gamma2', '60, 90', 'mean'}}, ...
         'ClusterFuncTime', 'none', ...
         'Measure', 'magnitude', ...
         'Output', 'all', ...
         'SaveKernel', 0));
% View results
hFigTf1 = view_surface_data([], sFilesHilbert.FileName);
hFigTf2 = view_timefreq(sFilesHilbert.FileName, 'SingleSensor', 4298);
figure_3d('SetStandardView', hFigTf1, 'left');
panel_surface('SetDataThreshold', hFigTf1, 1, 0.7);
panel_time('SetCurrentTime', 0.090);
panel_freq('SetCurrentFreq', 3);
bst_report('Snapshot', [hFigTf1 hFigTf2], sFilesHilbert.FileName, 'Hilbert transform');
bst_memory('UnloadAll', 'Forced');



%% ===== TUTORIAL #25: STATISTICS ====================================================
%  ===================================================================================
disp([10 'TODO> Tutorial #25: Statistics' 10]);



%% ===== TUTORIAL #26: CONNECTIVITY ==================================================
%  ===================================================================================
disp([10 'TODO> Tutorial #26: Connectivity' 10]);



%% ===== SAVE REPORT =====
% Save and display report
ReportFile = bst_report('Save', []);
bst_report('Open', ReportFile);


